project/src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 190)]
    private ?string $lastname = null;

    #[ORM\Column(length: 190, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 190, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 190)]
    private ?string $address = null;

    #[ORM\Column(length: 190)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 190)]
    private ?string $city = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isValid = null;

    #[ORM\Column(length: 190, nullable: true)]
    private ?string $phone = null;

    public function __toString()
     {
       return $this->lastname;
     }

    /**
 	*This constructor is for the date
 	*/
 	
 	public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();      
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isIsValid(): ?bool
    {
        return $this->isValid;
    }

    public function setIsValid(?bool $isValid): self
    {
        $this->isValid = $isValid;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
}

project/src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lastname', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlenght' => '2',
                    'maxlenght' => '190',
                ],
                'label' => 'Name',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ],
                
            ])
            ->add('firstname', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlenght' => '2',
                    'maxlenght' => '190',
                ],
                'label' => 'Vorname',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ],
                
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                    
                ],
                'label' => 'Beschreibung',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ]
            ])
            ->add('email', EmailType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'E-mail'
            ])             
            ->add('address', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlenght' => '2',
                    'maxlenght' => '190',
                ],
                'label' => 'Anschrift',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ],
                
            ])
            ->add('zipcode', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlenght' => '2',
                    'maxlenght' => '190',
                ],
                'label' => 'Postleitzahl',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ],
                
            ])
            ->add('city', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlenght' => '2',
                    'maxlenght' => '190',
                ],
                'label' => 'Stadt',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ],
                
            ])          
            ->add('phone', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlenght' => '2',
                    'maxlenght' => '190',
                ],
                'label' => 'Telefon',
                'label_attr' => [
                    'class' => 'form-label  mt-4'
                ],
                
            ])
             ->add('isValid', CheckboxType::class, [
                'attr' => [
                    'class' => 'form-check-input mt-4 ms-4',
                ],
                'required' => false,
                'label' => 'Geprüft?',
                'label_attr' => [
                    'class' => 'form-check-label mt-4'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

project/src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/kunden')]
class ClientController extends AbstractController
{
    #[Route('/', name: 'app_client_index', methods: ['GET'])]
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('pages/client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    #[Route('/neu', name: 'app_client_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ClientRepository $clientRepository): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->save($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pages/client/new.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_show', methods: ['GET'])]
    public function show(Client $client): Response
    {
        return $this->render('pages/client/show.html.twig', [
            'client' => $client,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_client_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->save($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pages/client/edit.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_delete', methods: ['POST'])]
    public function delete(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $clientRepository->remove($client, true);
        }

        return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
    }
}

project/templates/pages/client/_delete_form.html.twig
<form method="post" action="{{ path('app_client_delete', {'id': client.id}) }}" onsubmit="return confirm('Wollen Sie den Kunden löschen?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
	<button class="btn btn-danger btn-lg mt-4">Löschen</button>

</form>

project/templates/pages/client/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary btn-lg mt-4">{{ button_label|default('Speichern') }}</button>

{{ form_end(form) }}

project/templates/pages/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kunden ändern
{% endblock %}

{% block body %}
	<div class="container mt-4">
		<h1>Kunden ändern</h1>

		{{ include('pages/client/_form.html.twig', {'button_label': 'Ändern'}) }}

		<a class="btn btn-secondary btn-lg mt-4" href="{{ path('app_client_index') }}">Zurück</a>


		{{ include('pages/client/_delete_form.html.twig') }}</div>

{% endblock %}

project/templates/pages/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kunden Liste
{% endblock %}

{% block body %}
	<div class="container mt-4">
		<h1>Kunden Liste</h1>

		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Vorname</th>
					<th>Bemerkung</th>
					<th>Email</th>
					<th>Anschrift</th>
					<th>Postleitzahl</th>
					<th>Stadt</th>
					<th>Erstellung</th>
					<th>geprüft</th>
					<th>Telefon</th>
					<th>Aktion</th>
				</tr>
			</thead>
			<tbody>
				{% for client in clients %}
					<tr>
						<td>{{ client.lastname }}</td>
						<td>{{ client.firstname }}</td>
						<td>{{ client.description }}</td>
						<td>{{ client.email }}</td>
						<td>{{ client.address }}</td>
						<td>{{ client.zipcode }}</td>
						<td>{{ client.city }}</td>
						<td>{{ client.createdAt ? client.createdAt|date('d-m-Y ') : '' }}</td>
						<td>{{ client.isValid ? 'Yes' : 'No' }}</td>
						<td>{{ client.phone }}</td>
						<td>
							<a href="{{ path('app_client_show', {'id': client.id}) }}" class=' mt-4'>

								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewbox="0 0 16 16">
									<path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
									<path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/></svg>
							</a>


							<a href="{{ path('app_client_edit', {'id': client.id}) }}" class='mt-4 ms-4'>

								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewbox="0 0 16 16">
									<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
								</svg>
							</a>

						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="12">Kein Kunden</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<a class="btn btn-secondary btn-lg mt-4" href="{{ path('app_client_new') }}">Kunden erstellen</a>

	</div>

{% endblock %}

project/templates/pages/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kunden erstellen
{% endblock %}

{% block body %}
	<div class="container mt-4">
		<h1>Kunden erstellen</h1>

		{{ include('client/_form.html.twig') }}

		<a class="btn btn-secondary btn-lg mt-4" href="{{ path('app_client_index') }}">Zurück</a>

	</div>

{% endblock %}

project/templates/pages/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kunden
{% endblock %}

{% block body %}
	<div class="container mt-4">
		<h1>Kunden</h1>

		<table class="table">
			<tbody>

				<tr>
					<th>Name</th>
					<td>{{ client.lastname }}</td>
				</tr>
				<tr>
					<th>Vorname</th>
					<td>{{ client.firstname }}</td>
				</tr>
				<tr>
					<th>Bemerkung</th>
					<td>{{ client.description }}</td>
				</tr>
				<tr>
					<th>Email</th>
					<td>{{ client.email }}</td>
				</tr>
				<tr>
					<th>Anschrift</th>
					<td>{{ client.address }}</td>
				</tr>
				<tr>
					<th>Postleitzahl</th>
					<td>{{ client.zipcode }}</td>
				</tr>
				<tr>
					<th>Stadt</th>
					<td>{{ client.city }}</td>
				</tr>
				<tr>
					<th>Erstellung</th>
					<td>{{ client.createdAt ? client.createdAt|date('d-m-Y') : '' }}</td>
				</tr>
				<tr>
					<th>geprüft</th>
					<td>{{ client.isValid ? 'Yes' : 'No' }}</td>
				</tr>
				<tr>
					<th>Telefon</th>
					<td>{{ client.phone }}</td>
				</tr>
			</tbody>
		</table>

		<a class="btn btn-secondary btn-lg mt-4" href="{{ path('app_client_index') }}">Zurück</a>


		<a class="btn btn-primary btn-lg mt-4 ms-4" href="{{ path('app_client_edit', {'id': client.id}) }}">Ändern</a>


		{{ include('pages/client/_delete_form.html.twig') }}</div>

{% endblock %}